import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

// This runs in Node.js - Don't use client-side code here (browser APIs, JSX...)

/**
 * Sidebar structure for docs.lanonasis.com.
 *
 * Top-level categories (in order):
 *   1. Getting Started    — install + first memory + what's new
 *   2. Use Cases          — three primary journeys + first-memory example
 *   3. Memory Suite       — MaaS REST, SDK, CLI
 *   4. MCP                — server, tools, IDE integration
 *   5. Auth               — gateway, key contexts, device flow
 *   6. Vendor Keys        — upstream provider key manager
 *   7. v-secure           — preview surface
 *   8. Platform           — all 9 platform surfaces (architecture, onasis-core,
 *                            mcp-core, mcp-lanonasis, auth-gateway, control-room,
 *                            dashboard, lanonasis-index, vortexai-l0, v-secure)
 *   9. Operations         — operating the platform
 *  10. Security & Privacy — implementation + disclosure
 *  11. Guides             — migration, performance, vector search, realtime
 *  12. SDKs & Libraries   — TS, Python (Coming Soon), Go (Coming Soon), CLI,
 *                            security-sdk, ai-sdk, api-client, memory-sdk,
 *                            cli-sdk, oauth-client
 *  13. Reference          — autogenerated API, CLI reference, changelog,
 *                            migrations, support
 *
 * Removed:
 *   - The "Platform" category's "architecture only" entry. The audit found 9 of
 *     10 files in docs/platform/ were orphaned. The new Platform category lists
 *     them all.
 *   - "Tutorials" — the stock Docusaurus tutorial-basics / tutorial-extras
 *     directories were removed entirely.
 *   - "index.md" VitePress-orphan — deleted in P0.
 *
 * Auto-generated sidebar entries are still used for the API Reference and for
 * SDK sub-directories (sdks/cli/, sdks/python/, sdks/typescript/) so new
 * sub-pages appear without editing this file.
 */
const sidebars: SidebarsConfig = {
  docs: [
    {
      type: 'category',
      label: 'Getting Started',
      collapsed: false,
      items: [
        'getting-started/installation',
        'getting-started/quick-start',
        'getting-started/whats-new-2026-q1',
      ],
    },
    {
      type: 'category',
      label: 'Use Cases',
      items: [
        'use-cases/personal-knowledge',
        'use-cases/team-collaboration',
        'use-cases/customer-support',
        'examples/quickstart/first-memory',
      ],
    },
    {
      type: 'category',
      label: 'Memory Suite',
      collapsed: false,
      items: ['memory/overview', 'memory/rest-api', 'memory/sdk', 'memory/cli'],
    },
    {
      type: 'category',
      label: 'MCP (Model Context Protocol)',
      collapsed: false,
      items: [
        'mcp/overview',
        'mcp/production-server',
        'mcp/tools',
        'mcp/ide-integration',
      ],
    },
    {
      type: 'category',
      label: 'Auth',
      collapsed: false,
      items: [
        'auth/central-auth-gateway',
        'auth/key-contexts',
        'auth/device-flow',
      ],
    },
    {
      type: 'category',
      label: 'Vendor Keys',
      items: ['keys/vendor-key-management'],
    },
    {
      type: 'category',
      label: 'v-secure',
      collapsed: false,
      items: [
        'v-secure/intro',
        'v-secure/getting-started',
        'v-secure/installation',
        'v-secure/configuration',
        {
          type: 'category',
          label: 'API Reference',
          key: 'vsecure-api-reference',
          items: [
            'v-secure/api/overview',
            'v-secure/api/secrets',
            'v-secure/api/api-keys',
            'v-secure/api/mcp',
            'v-secure/api/audit-logs',
          ],
        },
        {
          type: 'category',
          label: 'v-secure Guides',
          items: [
            'v-secure/guides/secret-management',
            'v-secure/guides/mcp-integration',
          ],
        },
        {
          type: 'category',
          label: 'Compliance',
          items: ['v-secure/compliance/overview'],
        },
        {
          type: 'category',
          label: 'Examples',
          items: ['v-secure/examples/basic-usage'],
        },
      ],
    },
    {
      type: 'category',
      label: 'Platform Architecture',
      items: [
        'platform/architecture',
        'platform/onasis-core',
        'platform/mcp-core',
        'platform/mcp-lanonasis',
        'platform/auth-gateway',
        'platform/control-room',
        'platform/dashboard',
        'platform/lanonasis-index',
        'platform/v-secure',
        'platform/vortexai-l0',
      ],
    },
    {
      type: 'category',
      label: 'Operations',
      items: ['ops/operating-platform'],
    },
    {
      type: 'category',
      label: 'Security & Privacy',
      items: ['security/privacy-implementation'],
    },
    {
      type: 'category',
      label: 'Guides',
      items: [
        'guides/index',
        'guides/migration',
        'guides/performance',
        'guides/realtime-sync',
        'guides/vector-search',
      ],
    },
    {
      type: 'category',
      label: 'SDKs & Libraries',
      items: [
        'sdks/overview',
        'sdks/security-sdk',
        { type: 'autogenerated', dirName: 'sdks/typescript' },
        { type: 'autogenerated', dirName: 'sdks/python' },
        'sdks/go',
        { type: 'autogenerated', dirName: 'sdks/cli' },
        'sdks/ai-sdk',
        'sdks/api-client',
        'sdks/memory-sdk',
        'sdks/cli-sdk',
        'sdks/oauth-client',
      ],
    },
    {
      type: 'category',
      label: 'Reference',
      collapsed: false,
      items: [
        {
          type: 'category',
          label: 'API Reference',
          key: 'platform-api-reference',
          items: [{ type: 'autogenerated', dirName: 'api' }],
        },
        'cli/reference',
        'changelog',
        'changes/migrations',
        'support',
      ],
    },
  ],
};

export default sidebars;
