import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

// This runs in Node.js - Don't use client-side code here (browser APIs, JSX...)

/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */
const sidebars: SidebarsConfig = {
  tutorialSidebar: [
    {
      type: 'category',
      label: 'Platform',
      items: ['platform/architecture'],
    },
    {
      type: 'category',
      label: 'Auth',
      items: ['auth/central-auth-gateway'],
    },
    {
      type: 'category',
      label: 'MCP',
      items: ['mcp/production-server', 'mcp/ide-integration'],
    },
    {
      type: 'category',
      label: 'Memory Suite',
      items: ['memory/overview', 'memory/rest-api', 'memory/sdk', 'memory/cli'],
    },
    {
      type: 'category',
      label: 'Vendor Keys',
      items: ['keys/vendor-key-management'],
    },
    {
      type: 'category',
      label: 'Changelog & Migration',
      items: ['changes/index', 'changes/migrations'],
    },
    {
      type: 'category',
      label: 'Operations',
      items: ['ops/operating-platform'],
    },
    {
      type: 'category',
      label: 'Security & Privacy',
      items: ['security/privacy-implementation'],
    },
    {
      type: 'category',
      label: 'v-secure',
      collapsed: false,
      items: [
        'v-secure/intro',
        'v-secure/getting-started',
        'v-secure/installation',
        'v-secure/configuration',
        {
          type: 'category',
          label: 'API Reference',
          key: 'vsecure-api-reference',
          items: [
            'v-secure/api/overview',
            'v-secure/api/secrets',
            'v-secure/api/api-keys',
            'v-secure/api/mcp',
            'v-secure/api/audit-logs',
          ],
        },
        {
          type: 'category',
          label: 'Guides',
          items: [
            'v-secure/guides/secret-management',
            'v-secure/guides/mcp-integration',
          ],
        },
        {
          type: 'category',
          label: 'Compliance',
          items: [
            'v-secure/compliance/overview',
          ],
        },
        {
          type: 'category',
          label: 'Examples',
          items: [
            'v-secure/examples/basic-usage',
          ],
        },
      ],
    },
    {
      type: 'category',
      label: 'API Reference',
      key: 'platform-api-reference',
      items: [{ type: 'autogenerated', dirName: 'api' }],
    },
    {
      type: 'category',
      label: 'Tutorials',
      items: [
        { type: 'autogenerated', dirName: 'tutorial-basics' },
        { type: 'autogenerated', dirName: 'tutorial-extras' },
      ],
    },
  ],
};

export default sidebars;
